export const DISPLAY_ALERT = 'SHOW_ALERT'

export const HIDE_ALERT = 'REMOVE_ALERT'

export const ADVANCE_TOTAL_VALUE = "ADVANCE_TOTAL_VALUE";

export const GROUP_TOTAL_VALUE = "GROUP_TOTAL_VALUE";

export const TOTAL_COST_VALUE = "TOTAL_COST_VALUE ";

export const ADVANCE_PRICE_INPUT_VALUE = "ADVANCE_PRICE_INPUT_VALUE"

export const GROUP_PRICE_INPUT_VALUE = "GROUP_PRICE_INPUT_VALUE";

export const INCREMENT_ADVANCE_VALUE = "INCREMENT_ADVANCE_VALUE"

export const DECREMENT_ADVANCE_VALUE = "DECREMENT_ADVANCE_VALUE";

export const INCREMENT_GROUP_VALUE = "INCREMENT_GROUP_VALUE";

export const DECREMENT_GROUP_VALUE = "DECREMENT_GROUP_VALUE";

export const SELECTED_TICKETS = "SELECTED_TICKETS";
